// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahahwvadvtnavxzvessr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoYWh3dmFkdnRuYXZ4enZlc3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzkxMzAsImV4cCI6MjA2MDcxNTEzMH0.nDm46WYlPDch_vEEKtl-olE5tONL7DFO6NGlWdN83xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);